name: Build and Release .exe

on:
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境构建 .exe 文件
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # 指定 Python 版本

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Build the executable
      run: |
        pyinstaller --onefile --noconsole cloudflare_ddns.py  # 用 PyInstaller 打包成 exe 文件

    - name: Create Git tag for release
      run: |
        VERSION_TAG="v$(date +'%Y%m%d%H%M%S')"  # 使用当前时间戳作为版本号
        git tag $VERSION_TAG
        git push origin $VERSION_TAG

    - name: Upload .exe to Releases
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.create_tag.outputs.VERSION_TAG }}  # 使用自动生成的标签
        files: "dist/cloudflare_ddns.exe"  # 将打包后的 exe 文件上传到 Releases
